

export const locationFilter = {
    EN: [
        "",
        "Lei Yue Mun",
        "Tiu Keng Leng",
        "Aberdeen",
        "Tseung Kwan O",
        "Fanling",
        "South Kwai Chung",
        "North Point",
        "Cheung Chau",
        "City Hall",
        "Yuen Chau Kok",
        "Lockhart Road",
        "Yuen Long",
        "Tiu Keng Leng ",
        "Tung Chung",
        "Tuen Mun",
        "Sha Tin",
        "Quarry Bay",
        "Po On Road",
        "Sai Kung",
        "Ping Shan Tin Shui Wai",
        "Ngau Chi Wan",
        "Exhibition Gallery, Hong Kong Central Library",
        "To Kwa Wan",
        "Ma On Shan",
        "San Po Kong",
        "Tai Po",
        "Sheung Shui",
        "Tung Chung ",
        "Cheung Chau ",
        "Discovery Bay Alliance Church Community Centre Community Library",
        "Yau Ma Tei",
        "Fa Yuen Street",
        "Activity Room 1, Hong Kong Central Library",
        "North Kwai Chung",
        "Live At Zoom",
        "Ngau Tau Kok",
        "Yau Ma Tei ",
        "Tai Hing",
        "Lai Chi Kok",
        "Fa Yuen Street ",
        "Butterfly Estate",
        "Tuen Mun District Women's Association Peggy Lam Integrated Services Centre",
        "H.K.S.K.H. Tuen Mun Integrated Services Jockey Club Youth Express",
        "Lam Tin",
        "Chai Wan",
        "Shek Tong Tsui",
        "The Salvation Army - Tuen Mun East Integrated Service for Young People",
        "Shui Wo Street",
        "Tsing Yi",
        "Kowloon",
        "Tai Po Luk Heung Campus",
        "Fanling South",
        "Hong Kong Central Library",
        "Tsim Sha Tsui",
        "EKDRC Ltd Joyful Square",
        "KTC C.C. & M.A. Chuk Yuen Church Parent-child Activity Centre ",
        "Lok Fu",
        "Lung Hing",
        "Fu Shan",
        "Kowloon Tong Church of the C.C. & M.A Lau Ping Chai Study Center ",
        "The Salvation Army - Tuen Mun East Integrated Service for Young People",
        "Tai Kok Tsui",
        "Lok Kwan Social Service Tsz Wan Shan Centre",
        "Tsz Wan Shan",
        "Tsuen Wan",
        "Hung Hom",
        "Kowloon City",
        "Sham Shui Po"
    ],
    HK: [
        "",
        "鯉魚門",
        "調景嶺",
        "香港仔",
        "將軍澳",
        "粉嶺",
        "南葵涌",
        "北角",
        "長洲",
        "大會堂",
        "圓洲角",
        "駱克道",
        "元朗",
        "東涌",
        "屯門",
        "沙田",
        "鰂魚涌",
        "保安道",
        "西貢",
        "屏山天水圍",
        "牛池灣",
        "香港中央圖書館展覽館",
        "土瓜灣",
        "馬鞍山",
        "新蒲崗",
        "大埔",
        "上水",
        "基督教宣道會愉景灣堂服務中心社區圖書館",
        "油蔴地",
        "花園街",
        "香港中央圖書館1號活動室",
        "北葵涌",
        "Zoom直播",
        "牛頭角",
        "大興",
        "荔枝角",
        "蝴蝶邨",
        "屯門婦聯 - 林貝聿嘉綜合服務中心",
        "香港聖公會屯門綜合服務 - 賽馬會青年幹線",
        "藍田",
        "柴灣",
        "石塘咀",
        "救世軍屯門東青少年綜合服務",
        "瑞和街",
        "青衣",
        "九龍",
        "大埔六鄉學習園地",
        "粉嶺南",
        "香港中央圖書館",
        "尖沙咀",
        "東九龍居民委員會有限公司樂滿坊",
        "中華宣道會竹園堂親子活動中心",
        "樂富",
        "龍興",
        "富山",
        "九龍塘基督教中華宣道會竹園堂劉平齋閱覽室",
        "大角咀",
        "樂群社會服務處慈雲山服務中心",
        "慈雲山",
        "荃灣",
        "紅磡",
        "九龍城",
        "深水埗"
    ],
    CN: [
        "",
        "鯉魚門",
        "調景嶺",
        "香港仔",
        "將軍澳",
        "粉嶺",
        "南葵涌",
        "北角",
        "長洲",
        "大會堂",
        "圓洲角",
        "駱克道",
        "元朗",
        "東涌",
        "屯門",
        "沙田",
        "鰂魚涌",
        "保安道",
        "西貢",
        "屏山天水圍",
        "牛池灣",
        "香港中央圖書館展覽館",
        "土瓜灣",
        "馬鞍山",
        "新蒲崗",
        "大埔",
        "上水",
        "愉景灣",
        "油蔴地",
        "花園街",
        "香港中央圖書館1號活動室",
        "北葵涌",
        "Zoom直播",
        "牛頭角",
        "大興",
        "荔枝角",
        "蝴蝶邨",
        "屯門婦聯 - 林貝聿嘉綜合服務中心",
        "香港聖公會屯門綜合服務 - 賽馬會青年幹線",
        "藍田",
        "柴灣",
        "石塘咀",
        "救世軍屯門東青少年綜合服務",
        "瑞和街",
        "青衣",
        "九龍",
        "大埔六鄉學習園地",
        "粉嶺南",
        "香港中央圖書館",
        "尖沙咀",
        "東九龍居民委員會有限公司樂滿坊",
        "中華宣道會竹園堂親子活動中心",
        "樂富",
        "龍興",
        "富山",
        "九龍塘基督教中華宣道會竹園堂劉平齋閱覽室",
        "大角咀",
        "樂群社會服務處慈雲山服務中心",
        "慈雲山",
        "荃灣",
        "紅磡",
        "九龍城",
        "深水埗"
    ]
}